package com.example.biographyapp

import android.service.autofill.Validators.and

object PoliticsData {
   val politicsItems = listOf(PoliticsModel("Ellen Johnson Sirleaf",
   "ELLEN JOHNSON SIRLEAF (Born 29 October 1938)\n" +
           "Sirleaf was born in Monrovia in 1938. She attended the College of West Africa, a preparatory school, from 1948 to 1955. She married James Sirleaf when she was seventeen years old. The couple had four sons together, and she was primarily occupied as a homemaker. Early on in their marriage, James worked for the Department of Agriculture, and Sirleaf worked as a bookkeeper for an auto-repair shop.\n\n" +
           "She traveled with her husband to the United States in 1961 to continue her education and earned an associate degree in Accounting at Madison Business College, in Madison, Wisconsin. When they returned to Liberia, James continued his work in the Agriculture Department and Sirleaf pursued a career in the Treasury Department (Ministry of Finance). They divorced in 1961 because of James' abuse.\n\n" +
           "Sirleaf returned to college to finish her bachelor's degree. In 1970, she earned a BA in economics from the Economics Institute of the University of Colorado Boulder, where she also spent a summer preparing for graduate studies. Sirleaf studied Economics and Public policy at Harvard University's John F. Kennedy School of Government from 1969 to 1971, gaining a Master of Public Administration. She returned to her native Liberia to work in the administration of William Tolbert, where she was appointed as Assistant Minister of Finance. Whilst in that position, she attracted attention with a \"bombshell\" speech to the Liberian Chamber of Commerce that claimed that the country's corporations were harming the economy by hoarding or sending their profits overseas.\n\n" +
           "Sirleaf served as Assistant Minister from 1972 to 1973 in the Tolbert administration. She resigned after a disagreement about government spending. Subsequently, she was appointed as Minister of Finance a few years later, serving from 1979 to April 1980.\n" +
           "Master Sergeant Samuel Doe, a member of the indigenous Krahn ethnic group, seized power in a military coup on 12 April 1980; he ordered the assassination of Tolbert and execution by firing squad of all but four members of his Cabinet. The People's Redemption Council took control of the country and led a purge against the previous government. Sirleaf initially accepted a post in the new government as the President of the Liberian Bank for Development and Investment. She fled the country in November 1980 after publicly criticising Doe and the People's Redemption Council for their management of the country.\n\n" +
           "Sirleaf initially moved to Washington, D.C., and worked for the World Bank.[18] In 1981, she moved to Nairobi, Kenya to serve as Vice President of the African Regional Office of Citibank. She resigned from Citibank in 1985 following her involvement at the 1985 general election in Liberia. She went to work for Equator Bank, a subsidiary of HSBC.\n\n" +
           "In 1992, Sirleaf was appointed as the Director of the United Nations Development Programme's Regional Bureau for Africa at the rank of Assistant Administrator and Assistant Secretary General (ASG). She is internationally known as Africa's Iron Lady. This is due to her political prowess. She resigned from this role in 1997 in order to run for the presidency of Liberia. During her time at the UN, she was one of the seven internationally eminent persons designated in 1999 by the Organization of African Unity to investigate the Rwandan genocide, one of the five Commission Chairs for the Inter-Congolese Dialogue, and one of the two international experts selected by UNIFEM to investigate and report on the effect of conflict on women and women's roles in peace building. She was the initial Chairperson of the Open Society Initiative for West Africa (OSIWA) and a visiting Professor of Governance at the Ghana Institute of Management and Public Administration (GIMPA).\n\n" +
           "1985 general election\n" +
           "While working at Citibank, Sirleaf returned to Liberia in 1985 to run for Vice President under Jackson Doe on the ticket of the Liberian Action Party in the 1985 elections. However, Sirleaf was placed under house arrest in August 1985 and soon after sentenced to ten years in prison for sedition, as a consequence of a speech in which she insulted the members of the Samuel Doe regime. Following international calls for her release, Samuel Doe pardoned and released her in September. Due to government pressure, she was removed from the presidential ticket and instead ran for a Senate seat in Montserrado County.\n\n" +
           "In the 1985 elections, Samuel Doe and the National Democratic Party won the presidency and large majorities in both houses. The elections were widely condemned as neither free nor fair. Sirleaf was declared the winner of her Senate race, but she refused to accept the seat in protest of the election fraud.\n\n" +
           "After an attempted coup against the Doe government by Thomas Quiwonkpa on 12 November 1985, Sirleaf was arrested and imprisoned again on 13 November by Doe's forces. Despite continuing to refuse to accept her seat in the Senate, she was released in July 1986. She secretly fled the country to the United States later that year.\n\n" +
           "1997 presidential campaign\n" +
           "Sirleaf campaigning in Monrovia in 2005, shortly before she was elected\n\n" +
           "At the beginning of the First Liberian Civil War in 1989, Sirleaf supported Charles Taylor's rebellion against Doe. She helped raise money for the war and founded the National Patriotic Front of Liberia with Taylor and Tom Woewiyu. Because of this, Doe's government recommended that Sirleaf be banned from politics in Liberia for 30 years.\n\n" +
           "But, she later opposed Taylor's handling of the war and his treatment of rival opposition leaders such as Jackson Doe. By 1996, the presence of Economic Community of West African States (ECOWAS) peacekeepers led to a cessation of hostilities. The nation held the 1997 general election, which Sirleaf returned to Liberia to contest. She ran as the presidential candidate for the Unity Party and placed second in a controversial election, getting 25% of the vote to Charles Taylor's 75%. After controversy about the results and being accused of treason, Sirleaf left Liberia and went into exile in Abidjan, Ivory Coast.\n\n" +
           "2005 Presidential Campaign\n" +
           "After the end of the Second Liberian Civil War and the establishment of a transitional government, Sirleaf was proposed as a possible candidate for chairman of the government. Ultimately, Gyude Bryant, a political neutral, was chosen as chairman, while Sirleaf served as head of the Governance Reform Commission.\n\n" +
           "Sirleaf stood for president as the candidate of the Unity Party in the 2005 general election. She placed second in the first round of voting behind George Weah, a former footballer.[22] In the subsequent run-off election, Sirleaf earned 59% of the vote versus 40% for Weah, though Weah disputed the results.\n\n" +
           "The announcement of the new leader was postponed until further election investigations were carried out. On 23 November 2005, Sirleaf was declared the winner of the Liberian election and confirmed as the country's next president and the first woman to be elected as president of an African country. Her inauguration took place on 16 January 2006. It was attended by many foreign dignitaries, including United States Secretary of State Condoleezza Rice and First Lady Laura Bush.\n\n" +
           "2011 Presidential Campaign\n" +
           "In January 2010, Sirleaf announced that she would run for a second term in office in the 2011 presidential election while speaking to a joint session of the Legislature. Opposition leaders noted that in doing so, she had broken a promise made during her 2005 campaign to only serve one term if elected. Sirleaf was renominated as the Unity Party's presidential candidate at the party's national convention on 31 October 2010. That same day, Vice President Joseph Boakai was nominated by Sirleaf and confirmed by the delegates as Sirleaf's running mate.\n\n" +
           "The awarding of the Nobel Peace Prize to Sirleaf four days prior to the election sparked criticism from opposition parties, with Congress for Democratic Change candidate Winston Tubman calling the award \"undeserved\" and \"a political interference in our country's politics.\". Sirleaf called the timing of the award a coincidence and avoided mentioning the award during the final days of campaigning.\n" +
           "Sirleaf garnered 43.9% of the vote in the first round, more than any other candidate but short of the 50% needed to avoid a run-off. Tubman came in second with 32.7%, pitting him against Sirleaf in the second round. Tubman called for a boycott of the run-off, claiming that the results of the first round had been fraudulent. Sirleaf denied the allegations, and international observers reported that the first round election had been free, fair and transparent. As a result of the boycott, Sirleaf won the second round with 90.7% of the vote, though voter turnout significantly declined from the first round. Following the election, Sirleaf announced the creation of a \"national peace and reconciliation initiative,\" led by Nobel Peace Prize laureate Leymah Gbowee, to address the country's divisions and begin \"a national dialogue that would bring us together.\" She took the presidential oath for her second presidency on 16 January 2012.\n\n" +
           "2017 presidential campaign\n" +
           "Sirleaf crossed party lines to support George Weah in the 2017 presidential campaign. In the late evening hours of 13 January 2018, she along with some officials of the Unity Party were expelled by the National Executive Committee of the party, for failing to support Unity's presidential candidate, Joseph Boakai.",
   R.drawable.sirleaf),

       PoliticsModel("Kenneth Kaunda",
       "KENNETH KAUNDA (Born, 28 April 1924)\n" +
               "Kenneth Kaunda, in full Kenneth David Kaunda was the politician who led Zambia to independence in 1964 and served as that country’s president until 1991. Kaunda’s father, who was from Nyasaland (now Malawi), was a schoolteacher; his mother, also a teacher, was the first African woman to teach in colonial Zambia. Both taught among the Bemba ethnic group in northern Zambia, where young Kaunda received his early education, completing secondary school in the early 1940s. Like the majority of Africans in colonial Zambia who achieved some measure of middle-class status, he also began to teach, first in colonial Zambia and in the middle 1940s in Tanganyika (now Tanzania).\n\n" +
               "Struggle Against Colonial Rule\n" +
               "Kaunda returned to Zambia in 1949. In that year he became interpreter and adviser on African affairs to Sir Stewart Gore-Browne, a liberal white settler and a member of the Northern Rhodesian Legislative Council. Kaunda acquired knowledge of the colonial government as well as political skills, both of which served him well when later that year he joined the African National Congress (ANC), the first major anticolonial organization in Northern Rhodesia. In the early 1950s Kaunda became the ANC’s secretary-general, functioning as its chief organizing officer, a role that brought him into close contact with the movement’s rank and file. Thus, when the leadership of the ANC clashed over strategy in 1958–59, Kaunda carried a major part of the ANC operating structure into a new organization, the Zambia African National Congress. Kaunda became president of the new organization and skillfully used it to forge a militant policy against the British plan for a federation of the three central African colonies—Southern Rhodesia, Northern Rhodesia, and Nyasaland. African leaders opposed and feared any such federation because it would tend to place ultimate power in the hands of a white minority of settlers. Kaunda employed the Zambia congress as an instrument for executing what he called “positive nonviolent action,” a form of civil disobedience against the federation policy. His campaign had two major results: first, the British government modified the federation policy and eventually agreed to discard it; second, the imprisonment of Kaunda and other militant leaders elevated them to the status of national heroes in the eyes of the people. Thus, from 1960 on, the nationwide support of Zambia’s independence movement was secured, as was too the dominant status of Kenneth Kaunda in that movement. Kaunda was released from prison by the colonial government on January 8, 1960. At the end of that month he was elected president of the United National Independence Party (UNIP), which had been formed in October 1959 by Mainza Chona, a militant nationalist who was disenchanted with the older ANC. The UNIP enjoyed spectacular growth, claiming 300,000 members by June 1960. In December 1960 the British colonial authorities invited Kaunda and several other UNIP leaders to participate in discussions on the status of the three colonies at a conference in London. Early in the following year the British government announced that formal decolonization of Zambia would commence.\n\n" +
               "The first major elections leading to final decolonization were held in October 1962. The constitutional proposals upon which the election was based provided the European settlers in Northern Rhodesia with a disproportionate share of the votes. Yet the two major African parties—the UNIP and ANC—gained a majority of the votes. The UNIP was the winner, gaining 15 of the 37 seats in the new Legislative Council.\n\n" +
               "The UNIP’s success was attributed overwhelmingly to the leadership of Kaunda. He had been astute both in allaying the European settlers’ fears that an African regime would unfairly disregard their interests and in quelling the factionalism prevalent in large sections of the country’s African population. It was this same skill that enabled Kaunda to negotiate further constitutional advances, and in 1964 Zambia was granted independence with Kaunda as its president.\n\n" +
               "President of Zambia\n" +
               "Like other African leaders, Kaunda faced many complex post-independence problems, especially the issue of tribalism. He succeeded in continuing to negotiate on this issue, saving Zambia the trauma of tribal civil war. Nevertheless, interparty political violence occurred during the elections of 1968, in which Kaunda and his party were returned to power. In response, Kaunda in 1972 imposed one-party rule on Zambia, and in 1973 he introduced a new constitution that ensured his party’s uncontested rule.\n\n" +
               "In the 1970s Kaunda’s government acquired a majority interest in the country’s copper-mining operations and undertook to manage other industries as well. While investing large sums in the mining sector, the government neglected agriculture while nevertheless having to spend increasing sums on subsidized food for the urban poor. These policies reduced agricultural production and increased Zambia’s dependence on exports of copper and on foreign loans and aid. From the 1970s on, the result of these policies was the progressive impoverishment of Zambia; unemployment rose, living standards steadily declined, and the provision of education and other social services decayed. In foreign affairs, Kaunda led other countries of southern Africa in confronting the white-minority governments of Rhodesia (now Zimbabwe) and South Africa. He imposed economic sanctions against Rhodesia in the 1970s at great cost to his country’s own economy, and in the late 1970s he allowed Zambia to be used as a base by black nationalist guerrillas led by Joshua Nkomo.\n\n" +
               "In 1976 Kaunda assumed emergency powers, and he was reelected as president in one-candidate elections in 1978 and 1983. Several attempted coups against him in the early 1980s were squelched. The Zambian economy continued to deteriorate owing to a fall in the world price of copper (Zambia’s chief export), the rising price of oil (its chief import), the withdrawal of foreign aid and investment by developed countries, and worsening corruption within Kaunda’s government. With public dissatisfaction mounting and a credible political opposition in the process of formation, Kaunda in 1990 legalized opposition parties and set the stage for free, multiparty elections in 1991. In the elections, held late that year, Kaunda and the UNIP were defeated by the Movement for Multiparty Democracy (MMD) in a landslide. Kaunda’s successor, Frederick Chiluba, took office on November 2, 1991.\n\n" +
               "After the presidency\n" +
               "After leaving office, Kaunda clashed frequently with Chiluba’s government and the MMD. He planned to run against Chiluba in the 1996 presidential election but was barred from doing so after constitutional amendments were passed that made him ineligible. On December 25, 1997, Kaunda was arrested on charges of inciting an attempted coup that had occurred earlier that year in October. He was released six days later, but he was placed under house arrest until all charges were withdrawn in June 1998. The next month, Kaunda announced that he would resign from his role as UNIP’s president once a successor was chosen. However, the lack of agreement regarding his successor caused a rift within the UNIP, and ultimately Kaunda did not resign until 2000. In March 1999 a judge ruled that Kaunda should be stripped of his Zambian citizenship because his parents were from Malawi and, furthermore, because of that fact, Kaunda had held office illegally for most of his period in government. Kaunda mounted a challenge, and his citizenship was restored the next year when the petition that generated the court ruling was withdrawn.\n\n" +
               "In 2002 Kaunda was appointed the Balfour African President-in-Residence at Boston University in the United States, a position he held until 2004. In 2003 he was awarded the Grand Order of the Eagle in Zambia by Chiluba’s successor, Pres. Levy Mwanawasa.\n",
       R.drawable.kaunda),

       PoliticsModel("Jomo Kenyatta",
       "JOMO KENYATTA (1894 - August 22, 1978)\n" +
               "Jomo Kenyatta, original name Kamau Ngengi, was born in Ichaweri, British East Africa (now Kenya)in 1894 was an African statesman and nationalist, the first prime minister (1963–64) and then the first president (1964–78) of independent Kenya.\n\n" +
               "Kenyatta was born as Kamau, son of Ngengi, at Ichaweri, southwest of Mount Kenya in the East African highlands. His father was a leader of a small Kikuyu agricultural settlement. About age 10 Kamau became seriously ill with jigger infections in his feet and one leg, and he underwent successful surgery at a newly established Church of Scotland mission. This was his initial contact with Europeans. Fascinated with what he had seen during his recuperation, Kamau ran away from home to become a resident pupil at the mission. He studied the Bible, English, mathematics, and carpentry and paid his fees by working as a houseboy and cook for a European settler. In August 1914 he was baptized with the name Johnstone Kamau. He was one of the earliest of the Kikuyu to leave the confines of his own culture. And, like many others, Kamau soon left the mission life for the urban attractions of Nairobi.\n" +
               "There he secured a job as a clerk in the Public Works Department, and he also adopted the name Kenyatta, the Kikuyu term for a fancy belt that he wore. After serving briefly as an interpreter in the High Court, Kenyatta transferred to a post with the Nairobi Town Council. About this time, he married and began to raise a family.\n\n" +
               "The first African political protest movement in Kenya against a white-settler-dominated government began in 1921—the East Africa Association (EAA), led by an educated young Kikuyu named Harry Thuku. Kenyatta joined the following year. One of the EAA’s main purposes was to recover Kikuyu lands lost when Kenya became a British crown colony (1920). The Africans were dispossessed, leaseholds of land were restricted to white settlers, and native reservations were established. In 1925 the EAA disbanded as a result of government pressures, and its members re-formed as the Kikuyu Central Association (KCA). Three years later Kenyatta became this organization’s general secretary, though he had to give up his municipal job as a consequence.\n\n" +
               "In May 1928 Kenyatta launched a monthly Kikuyu-language newspaper called Mwigithania (“He Who Brings Together”), aimed at gaining support from all sections of the Kikuyu. The paper was mild in tone, preaching self-improvement, and was tolerated by the government. But soon a new challenge appeared. A British commission recommended a closer union of the three East African territories (Kenya, Uganda, Tanganyika). British settler leaders supported the proposal, expecting that internal self-government might follow. To the KCA such a prospect looked disastrous for Kikuyu interests; in February 1929 Kenyatta went to London to testify against the scheme, but in London the secretary of state for colonies refused to meet with him.\n" + "In March 1930 Kenyatta wrote an eloquent letter in The Times of London setting out five issues championed by the KCA:\n" + "(1) security of land tenure and the return of lands allotted to European settlers \n" +"(2) increased educational facilities\n"+ "(3) repeal of hut taxes on women, which forced some to earn money by prostitution"+  "(4) African representation in the Legislative Council \n" + "(5) noninterference with traditional customs.\n" + "He concluded by saying that the lack of these measures “must inevitably result in a dangerous explosion—the one thing all sane men wish to avoid.”\n\n" +
               "Again in 1931 Kenyatta’s testimony on the issue of closer union of the three colonies was refused, despite the help of liberals in the House of Commons. In the end, however, the government temporarily abandoned its plan for union. Kenyatta did manage to testify on behalf of Kikuyu land claims in 1932 at hearings of the Carter Land Commission. The commission decided to offer compensation for some appropriated territories but maintained the “white highlands” policy, which restricted the Kikuyu to overcrowded reserves. Kenyatta subsequently visited the Soviet Union (he spent two years at Moscow State University) and traveled extensively through Europe; on his return to England he studied anthropology under Bronisław Malinowski at the London School of Economics. His thesis was revised and published in 1938 as Facing Mount Kenya, a study of the traditional life of the Kikuyu characterized by both insight and a tinge of romanticism. This book signaled another name change, to Jomo (“Burning Spear”) Kenyatta.\n\n" +
               "During the 1930s Kenyatta briefly joined the Communist Party, met other black nationalists and writers, and organized protests against the Italian invasion of Ethiopia. The onset of World War II temporarily cut him off from the KCA, which was banned by the Kenya authorities as potentially subversive. Kenyatta maintained himself in England by lecturing and working as a farm labourer, and he continued to produce political pamphlets publicizing the Kikuyu cause.\n\n" +
               "Kenyatta helped organize the fifth Pan-African Congress, which met in Manchester, England, on October 15–18, 1945, with W.E.B. Du Bois of the United States in the chair; Kwame Nkrumah, the future leader of Ghana, was also present. Resolutions were passed and plans discussed for mass nationalist movements to demand independence from colonial rule.\n",
       R.drawable.kenyatta),

       PoliticsModel("Thomas Isidore Noel Sankara",
       "THOMAS ISIDORE NOEL SANKARA (December 21st, 1949 – October 15,1987)\n" +
               "Thomas Isidore Noel Sankara, born in Yako, Upper Volta (now Burkina Faso) was a military officer and proponent of Pan-Africanism who was installed as president of Upper Volta (later Burkina Faso) in 1983 after a military coup. He held that position until 1987, when he was killed during another coup.\n\n" +
               "Sankara’s Roman Catholic parents wanted him to be a priest, but he opted for a military career instead. In 1970, at the age of 20, Sankara was sent for officer training in Madagascar, where he witnessed a popular uprising of students and workers that succeeded in toppling Madagascar’s government. Before returning to Upper Volta in 1972, Sankara attended a parachute academy in France, where he was further exposed to left-wing political ideologies. In 1974 he earned much public attention for his heroic performance in the border war with Mali, but years later he would renounce the war as useless and unjust.\n\n" +
               "By the early 1980s, Burkina Faso was being rocked by a series of labour union strikes and military coups. Sankara’s military achievements and charismatic leadership style made him a popular choice for political appointments, but his personal and political integrity put him at odds with the leadership of the successive military governments that came to power, leading to his arrest on several occasions. In January 1983, Sankara was selected as the prime minister of the newly formed Council for the Salvation of the People (Conseil de Salut du Peuple; CSP), headed by Jean-Baptiste Ouédraogo. This post provided him with an entryway into international politics and a chance to meet with leaders of the nonaligned movement, including Fidel Castro (Cuba), Samora Machel (Mozambique), and Maurice Bishop (Grenada). Sankara’s anti-imperialist stance and grassroots popularity increasingly put him at odds with conservative elements within the CSP, including President Ouédraogo. Sankara was removed as prime minister in May and arrested once again. On August 4, 1983, Blaise Compaoré, Sankara’s close friend and fellow army colleague, led a group that freed Sankara, overthrew the Ouédraogo regime, and formed the National Council of the Revolution (Conseil National de la Révolution) with Sankara as its president.\n\n" +
               "Sankara declared the objectives of the “democratic and popular revolution” to be primarily concerned with the tasks of eradicating corruption, fighting environmental degradation, empowering women, and increasing access to education and health care, with the larger goal of liquidating imperial domination. During the course of his presidency, Sankara successfully implemented programs that vastly reduced infant mortality, increased literacy rates and school attendance, and boosted the number of women holding governmental posts. On the environmental front, in the first year of his presidency alone 10 million trees were planted in an effort to combat desertification. On the first anniversary of the coup that had brought him to power, he changed the country’s name from Upper Volta to Burkina Faso, which means roughly “land of upright people” in Mossi and Dyula, the country’s two most widely spoken indigenous languages.\n\n" +
               "Despite the great strides that were made, there was growing dissent in the country, partly because of economic problems and opposition from traditional quarters to some of Sankara’s more progressive social policies. His administration gradually lost popular support, and internal conflict within his government grew as well. On October 15, 1987, Sankara was assassinated in a coup led by Compaoré and two others.\n",
       R.drawable.thomas),

       PoliticsModel("Kofi Annan",
       "KOFI ANNAN (April 8, 1938- August 18, 2018),\n" +
               "Kofi Annan, in full Kofi Atta Annan, born in  Kumasi, Gold Coast [now Ghanaian international civil servant, who was the secretary-general of the United Nations (UN) from 1997 to 2006. He was the corecipient, with the United Nations, of the Nobel Prize for Peace in 2001.\n\n" +
               "Annan, whose father was governor of Asante province and a hereditary paramount chief of the Fante people, studied at the University of Science and Technology in Kumasi before enrolling at Macalester College in St. Paul, Minnesota, U.S., where he received a bachelor’s degree in economics. He continued his studies at the Institute for Advanced International Studies in Geneva. He earned a master’s degree while a Sloan fellow at the Massachusetts Institute of Technology in 1971–72.\n\n" +
               "Annan began his career with the UN as a budget officer for the World Health Organization in Geneva in 1962. With the exception of a brief stint as the director of tourism in Ghana (1974–76), he spent his entire career with the UN, serving in several administrative posts. On March 1, 1993, he was elevated to undersecretary-general for peacekeeping operations. In that position he distinguished himself during the civil war in Bosnia and Herzegovina, particularly in his skillful handling of the transition of peacekeeping operations from UN forces to NATO forces.\n\n" +
               "Because Boutros Boutros-Ghali, Annan’s predecessor as secretary-general, had alienated some member nations—most notably the United States—with his independent and aloof style, Annan entered office with the tasks of repairing relations with the United States and reforming the UN bureaucracy. Soon after becoming secretary-general, he introduced a reform plan that sought to reduce the organization’s budget and streamline its operations, moves that were welcomed by the United States. Other priorities included restoring public confidence in the UN, combating the AIDS virus, especially in Africa, and ending human rights abuses.\n\n" +
               "In 2001 Annan was appointed to a second term. Later that year the September 11 attacks occurred in the United States, and global security and terrorism became major issues for Annan. In 2003 the United States launched a war against Iraq without receiving approval from the UN Security Council, and Annan’s subsequent criticism of the war strained relations with the United States (see Iraq War). Later in 2003 Annan appointed a panel to explore the UN’s response to global threats, and he included many of its recommendations in a major reform package presented to the UN General Assembly in 2005. A number of measures were later adopted; the proposal to expand the Security Council from 15 to 24 members was among those rejected. In 2005 Annan was at the centre of controversy following an investigation into the oil-for-food program, which had allowed Iraq—under UN supervision—to sell a set amount of oil in order to purchase food, medicine, and other necessities. A report described major corruption within the program and revealed that Annan’s son was part of a Swiss business that had won an oil-for-food contract. Although Annan was cleared of wrongdoing, he was criticized for his failure to properly oversee the program. In 2006 Annan’s term ended, and he was succeeded by Ban Ki-Moon.\n\n" +
               "In 2007 Annan was named chairperson of the Alliance for a Green Revolution in Africa (AGRA), an organization aiding small-scale farmers; AGRA was funded by the Bill & Melinda Gates Foundation and the Rockefeller Foundation. He later played a crucial role in resolving the Kenyan election crisis that began in late December 2007, eventually brokering a power-sharing agreement between the government and the opposition on February 28, 2008. In the same year, he received the Peace of Westphalia Prize, awarded biannually for contributions to unity and peace in Europe, and became chancellor of the University of Ghana. In 2007 he founded the Kofi Annan Foundation, a not-for-profit organization that promotes peace, sustainable development, human rights, and the rule of law.\n\n" +
               "In February 2012 Annan was appointed Joint Special Envoy for Syria by the United Nations and the League of Arab States. His core diplomatic effort consisted in delivering to the Syrian government a six-point proposal for ending the country’s civil war, a plan endorsed by the Security Council. The proposal enjoined Pres. Bashar al-Assad’s government to take significant steps, including ending all fighting operations. The Syrian government formally accepted the plan in March but continued its attacks on rebel forces and on popular demonstrations. In August Annan announced his demission as Joint Special Envoy, citing a lack of unity and political will among world powers to resolve the conflict.\n\n" +
               "Annan coauthored a number of works. The memoir Interventions: A Life in War and Peace (cowritten with Nader Mousavizadeh) was published in 2012.\n",
       R.drawable.kofi),

       PoliticsModel("Nelson Mandela",
       "NELSON MANDELA (July 18, 1918 – December 5, 2013)\n" +
               "Nelson Mandela, in full Nelson Rolihlahla Mandela, byname Madiba, was born in Mvezo, South Africa. Black nationalist and the first Black president of South Africa (1994–99). His negotiations in the early 1990s with South African Pres. F.W. de Klerk helped end the country’s apartheid system of racial segregation and ushered in a peaceful transition to majority rule. Mandela and de Klerk were jointly awarded the Nobel Prize for Peace in 1993 for their efforts.\n\n" +
               "Nelson Mandela was the son of Chief Henry Mandela of the Madiba clan of the Xhosa-speaking Tembu people. After his father’s death, young Nelson was raised by Jongintaba, the regent of the Tembu. Nelson renounced his claim to the chieftainship to become a lawyer. He attended South African Native College (later the University of Fort Hare) and studied law at the University of the Witwatersrand; he later passed the qualification exam to become a lawyer. In 1944 he joined the African National Congress (ANC), a Black-liberation group, and became a leader of its Youth League. That same year he met and married Evelyn Ntoko Mase. Mandela subsequently held other ANC leadership positions, through which he helped revitalize the organization and oppose the apartheid policies of the ruling National Party.\n\n" +
               "In 1952 in Johannesburg, with fellow ANC leader Oliver Tambo, Mandela established South Africa’s first Black law practice, specializing in cases resulting from the post-1948 apartheid legislation. Also that year, Mandela played an important role in launching a campaign of defiance against South Africa’s pass laws, which required nonwhites to carry documents (known as passes, pass books, or reference books) authorizing their presence in areas that the government deemed “restricted” (i.e., generally reserved for the white population). He traveled throughout the country as part of the campaign, trying to build support for nonviolent means of protest against the discriminatory laws. In 1955 he was involved in drafting the Freedom Charter, a document calling for nonracial social democracy in South Africa.\n\n" +
               "Mandela’s antiapartheid activism made him a frequent target of the authorities. Starting in 1952, he was intermittently banned (severely restricted in travel, association, and speech). In December 1956 he was arrested with more than 100 other people on charges of treason that were designed to harass antiapartheid activists. Mandela went on trial that same year and eventually was acquitted in 1961. During the extended court proceedings, he divorced his first wife and married Nomzamo Winifred Madikizela (Winnie Madikizela-Mandela).\n\n" +
               "Underground activity and the Rivonia Trial\n" +
               "After the massacre of unarmed Black South Africans by police forces at Sharpeville in 1960 and the subsequent banning of the ANC, Mandela abandoned his nonviolent stance and began advocating acts of sabotage against the South African regime. He went underground (during which time he became known as the Black Pimpernel for his ability to evade capture) and was one of the founders of Umkhonto we Sizwe (“Spear of the Nation”), the military wing of the ANC. In 1962 he went to Algeria for training in guerrilla warfare and sabotage, returning to South Africa later that year. On August 5, shortly after his return, Mandela was arrested at a road block in Natal; he was subsequently sentenced to five years in prison.\n\n" +
               "In October 1963 the imprisoned Mandela and several other men were tried for sabotage, treason, and violent conspiracy in the infamous Rivonia Trial, named after a fashionable suburb of Johannesburg where raiding police had discovered quantities of arms and equipment at the headquarters of the underground Umkhonto we Sizwe. Mandela’s speech from the dock, in which he admitted the truth of some of the charges made against him, was a classic defense of liberty and defiance of tyranny. (His speech garnered international attention and acclaim and was published later that year as I Am Prepared to Die.) On June 12, 1964, he was sentenced to life imprisonment, narrowly escaping the death penalty.\n\n" +
               "Incarceration\n" +
               "From 1964 to 1982 Mandela was incarcerated at Robben Island Prison, off Cape Town. He was subsequently kept at the maximum-security Pollsmoor Prison until 1988, when, after being treated for tuberculosis, he was transferred to Victor Verster Prison near Paarl. The South African government periodically made conditional offers of freedom to Mandela, most notably in 1976, on the condition that he recognize the newly independent—and highly controversial—status of the Transkei Bantustan and agree to reside there. An offer made in 1985 required that he renounce the use of violence. Mandela refused both offers, the second on the premise that only free men were able to engage in such negotiations and, as a prisoner, he was not a free man.\n\n" +
               "Throughout his incarceration, Mandela retained wide support among South Africa’s Black population, and his imprisonment became a cause célèbre among the international community that condemned apartheid. As South Africa’s political situation deteriorated after 1983, and particularly after 1988, he was engaged by ministers of Pres. P.W. Botha’s government in exploratory negotiations; he met with Botha’s successor, de Klerk, in December 1989.\n\n" +
               "On February 11, 1990, the South African government under President de Klerk released Mandela from prison. Shortly after his release, Mandela was chosen deputy president of the ANC; he became president of the party in July 1991. Mandela led the ANC in negotiations with de Klerk to end apartheid and bring about a peaceful transition to nonracial democracy in South Africa.\n\n" +
               "Presidency and retirement\n" +
               "In April 1994 the Mandela-led ANC won South Africa’s first elections by universal suffrage, and on May 10 Mandela was sworn in as president of the country’s first multiethnic government. He established in 1995 the Truth and Reconciliation Commission (TRC), which investigated human rights violations under apartheid, and he introduced housing, education, and economic development initiatives designed to improve the living standards of the country’s Black population. In 1996 he oversaw the enactment of a new democratic constitution. Mandela resigned his post with the ANC in December 1997, transferring leadership of the party to his designated successor, Thabo Mbeki. Mandela and Madikizela-Mandela had divorced in 1996, and in 1998 Mandela married Graca Machel, the widow of Samora Machel, the former Mozambican president and leader of Frelimo.\n\n" +
               "Mandela did not seek a second term as South African president and was succeeded by Mbeki in 1999. After leaving office Mandela retired from active politics but maintained a strong international presence as an advocate of peace, reconciliation, and social justice, often through the work of the Nelson Mandela Foundation, established in 1999. \n\n" +
               "Mandela Day, observed on Mandela’s birthday, was created to honour his legacy by promoting community service around the world. It was first observed on July 18, 2009, and was sponsored primarily by the Nelson Mandela Foundation and the 46664 initiative (the foundation’s HIV/AIDS global awareness and prevention campaign); later that year the United Nations declared that the day would be observed annually as Nelson Mandela International Day.\n\n",
       R.drawable.mandela),

       PoliticsModel("Kwame Nkrumah",
       "KWAME NKRUMAH (21 September 1909 – 27 April 1972)\n" +
               "Kwame Nkrumah was a Ghanaian politician, political theorist, and revolutionary. He was the first Prime Minister and President of Ghana, having led the Gold Coast to independence from Britain in 1957. An influential advocate of Pan-Africanism, Nkrumah was a founding member of the Organization of African Unity and winner of the Lenin Peace Prize from the Soviet Union in 1962.\n\n" +
               "After twelve years abroad pursuing higher education, developing his political philosophy, and organizing with other diasporic pan-Africanists, Kwame Nkrumah returned to the Gold Coast to begin his political career as an advocate of national independence. He formed the Convention People's Party, which achieved rapid success through its unprecedented appeal to the common voter. He became Prime Minister in 1952 and retained the position when Ghana declared independence from Britain in 1957. In 1960, Ghanaians approved a new constitution and elected Nkrumah President.\n\n" +
               "His administration was primarily socialist as well as nationalist. It funded national industrial and energy projects, developed a strong national education system and promoted a pan-Africanist culture. Under Nkrumah, Ghana played a leading role in African international relations during the decolonization period.\n\n" +
               "In 1964, a constitutional amendment made Ghana a one-party state, with Nkrumah as president for life of both the nation and its party. Nkrumah was deposed in 1966 by the National Liberation Council which under the supervision of international financial institutions privatized many of the country's state corporations. Nkrumah lived the rest of his life in Guinea, of which he was named honorary co-president.\n",
       R.drawable.nkrumah),

       PoliticsModel("Julius Nyerere",
       "JULIUS NYERERE (13 April 1922 – 14 October 1999)\n" +
               "Julius Kambarage Nyerere was a Tanzanian anti-colonial activist, politician, and political theorist. He governed Tanganyika as Prime Minister from 1961 to 1962 and then as President from 1963 to 1964, after which he led its successor state, Tanzania, as President from 1964 to 1985. He was a founding member and chair of the Tanganyika African National Union (TANU) party, and of its successor Chama Cha Mapinduzi, from 1954 to 1990. Ideologically an African nationalist and African socialist, he promoted a political philosophy known as Ujamaa.\n\n" +
               "Born in Butiama,Mara,Tanganyika. Nyerere was the son of a Zanaki chief. After completing his schooling, he studied at Makerere College in Uganda and then Edinburgh University in Scotland. In 1952 he returned to Tanganyika, married, and worked as a teacher. In 1954, he helped form TANU, through which he campaigned for Tanganyikan independence from the British Empire. Influenced by the Indian independence leader Mahatma Gandhi, Nyerere preached non-violent protest to achieve this aim. Elected to the Legislative Council in the 1958–1959 elections, Nyerere then led TANU to victory at the 1960 general election, becoming Prime Minister. Negotiations with the British authorities resulted in Tanganyikan independence in 1961. In 1962, Tanganyika became a republic, with Nyerere elected its first president. His administration pursued decolonisation and the \"Africanisation\" of the civil service while promoting unity between indigenous Africans and the country's Asian and European minorities. He encouraged the formation of a one-party state and unsuccessfully pursued the Pan-Africanist formation of an East African Federation with Uganda and Kenya. A 1963 mutiny within the army was suppressed with British assistance.\n\n" +
               "Following the Zanzibar Revolution of 1964, the island of Zanzibar was unified with Tanganyika to form Tanzania. After this, Nyerere placed a growing emphasis on national self-reliance and socialism. Although his socialism differed from that promoted by Marxism–Leninism, Tanzania developed close links with Mao Zedong's Marxist-governed China. In 1967, Nyerere issued the Arusha Declaration which outlined his vision of ujamaa. Banks and other major industries and companies were nationalised; education and healthcare were significantly expanded. Renewed emphasis was placed on agricultural development through the formation of communal farms, although these reforms hampered food production and left areas dependent on food aid. His government provided training and aid to anti-colonialist groups fighting white-minority rule throughout southern Africa and oversaw Tanzania's 1978–1979 war with Uganda which resulted in the overthrow of Ugandan President Idi Amin. In 1985, Nyerere stood down and was succeeded by Ali Hassan Mwinyi, who reversed many of Nyerere's policies. He remained chair of Chama Cha Mapinduzi until 1990, supporting a transition to a multi-party system, and later served as mediator in attempts to end the Burundian Civil War.\n\n" +
               "Nyerere was a controversial figure. Across Africa he gained widespread respect as an anti-colonialist and in power received praise for ensuring that, unlike many of its neighbours, Tanzania remained stable and unified in the decades following independence. His construction of the one-party state and use of detention without trial led to accusations of dictatorial governance, while he has also been blamed for economic mismanagement. He is held in deep respect within Tanzania, where he is often referred to by the Swahili honorific Mwalimu (\"teacher\") and described as the \"Father of the Nation\".\n",
       R.drawable.nyerere),

       PoliticsModel("Patrice Lumumba",
       "PATRICE LUMUMBA (July 2, 1925 - January 17, 1961)\n" +
               "Patrice Émery alternatively styled Patrice Hemery Lumumba was a Congolese politician and independence leader who served as the first Prime Minister of the independent Democratic Republic of the Congo (then Republic of the Congo) from June until September 1960. He played a significant role in the transformation of the Congo from a colony of Belgium into an independent republic. Ideologically an African nationalist and pan-Africanist, he led the Congolese National Movement (MNC) party from 1958 until his assassination.\n\n" +
               "Shortly after Congolese independence in 1960, a mutiny broke out in the army, marking the beginning of the Congo Crisis. Lumumba appealed to the United States and the United Nations for help to suppress the Belgian-supported Katangan secessionists led by Moïse Tshombe. Both refused due to suspicions among the Western world that Lumumba ambiguously held pro-communist views. These suspicions appeared to be supported when Lumumba turned to the Soviet Union for assistance, which the CIA described as a \"classic communist takeover\". This led to growing differences with President Joseph Kasa-Vubu and chief-of-staff Joseph-Désiré Mobutu, as well as with the United States and Belgium, who opposed the Soviet Union in the Cold War.\n\n" +
               "After Mobutu's military coup, Lumumba attempted to escape to Stanleyville to join his supporters who had established a new anti-Mobutu rival state called the Free Republic of the Congo. However, Lumumba was subsequently captured and imprisoned enroute by state authorities under Mobutu and executed by a firing squad under the command of Katangan authorities. Following his assassination, he was widely seen as a martyr for the wider Pan-African movement. In 2002, Belgium formally apologized for its role in the assassination.\n\n",
       R.drawable.lumumba),

       PoliticsModel("Haile Selassie",
           "HAILE SELASSIE (July 23, 1892 - August 27, 1975) \n" +
                   "Haile Selassie I was Ethiopia's 225th and last emperor, serving from 1930 until his overthrow by the Marxist dictator Mengistu Haile Mariam in 1974. The longtime ruler traced his line back to Menelik I, who was credited with being the child of King Solomon and the Queen of Sheba.\n\n" +
                   "He was born in a mud hut in Ejersa Gora on July 23, 1892. Originally named Lij Tafari Makonnen, he was the only surviving and legitimate son of Ras Makonnen, the governor of Harar. Among his father's important allies was his cousin, Emperor Menelik II, who did not have a male heir to succeed him. Tafari seemed like a possible candidate when, following his father's death in 1906, he was taken under the wing of Menelik. In 1913, however, after the passing of Menelik II, it was the emperor's grandson, Lij Yasu, not Tafari, who was appointed as emperor. But Yasu, who maintained a close association with Islam, never gained favor with Ethiopia's majority Christian population. As a result Tafari became the face of the opposition, and in 1916 he took power from Lij Yasu and imprisoned him for life. The following year Menelik II's daughter, Zauditu, became empress, and Tafari was named regent and heir apparent to the throne.\n\n" +
                   "For a country trying to gain its foothold in the young century and curry favor with the West, the progressive Tafari came to symbolize the hopes and dreams of Ethiopia's younger population. In 1923 he led Ethiopia into the League of Nations. The following year, he traveled to Europe, becoming the first Ethiopian ruler to go abroad. His power only grew. In 1928 he appointed himself king, and two years later, after the death of Zauditu, he was made emperor and assumed the name Haile Selassie (\"Might of the Trinity\").\n\n" +
                   "Over the next four decades, Haile Selassie presided over a country and government that was an expression of his personal authority. His reforms greatly strengthened schools and the police, and he instituted a new constitution and centralized his own power.\n\n" +
                   "In 1936 he was forced into exile after Italy invaded Ethiopia. Haile Selassie became the face of the resistance as he went before the League of Nations in Geneva for assistance, and eventually secured the help of the British in reclaiming his country and reinstituting his powers as emperor in 1941.\n\n" +
                   "Haile Selassie again moved to try to modernize his country. In the face of a wave of anti-colonialism sweeping across Africa, he granted a new constitution in 1955, one that outlined equal rights for his citizens under the law, but conversely did nothing to diminish Haile Selassie's own powers.\n\n" +
                   "By the early 1970s famine, ever-worsening unemployment and increasing frustration with the government's inability to respond to the country's problems began to undermine Haile Selassie's rule. In February 1974 mutinies broke out in the army over low pay, while a secessionist guerrilla war in Eritrea furthered his problems. Haile Selassie was eventually ousted from power in a coup and kept under house arrest in his palace until his death in 1975. Reports initially circulated claiming that he had died of natural causes, but later evidence revealed that he had probably been strangled to death on the orders of the new government.\n\n" +
                   "In 1992 Haile Selassie's remains were discovered, buried under a toilet in the Imperial Palace. In November 2000 the late emperor received a proper burial when his body was laid to rest in Addis Ababa's Trinity Cathedral.\n",
           R.drawable.haile)
   
   )
}