package com.example.biographyapp

object TechData {
    val techItems = listOf(
            TechModel("Jason Njoku",
            "JASON NJOKU (born 11th December 1980)\n" +
                    "Jason was born and raised in Deptford, South East London, and His mother raised him and his three sisters and brother by herself, whilst working a full-time job in the National Health Service. He attended school in London, then moved to a village in Nigeria from the age of 12 – 15. After he returned from Nigeria, he attended college to complete his A-Levels, before securing a place at The University of Manchester where he read Chemistry. He graduated in 2005 with a 2:1 and launched Brash Magazine, a student publication which ran for three years before it closed in 2008. \n\n" +
                    "After a number of failed enterprises between 2005 and 2010, which included a blog network, a T-shirt business and a web design company, Njoku moved back home into his mother's house in Deptford. It was there that he came up with the idea of starting a Nollywood online distribution business, \"The West had Hulu and Netflix – Africa had nothing\", notes Njoku. Having studied the industry from afar, he flew to Lagos, thanks to the financial help of his best friend Bastian Gotter, a fellow University of Manchester graduate, and started purchasing the online licences of Nollywood movies. He worked from a two-bedroom apartment in Festac, Lagos, and struck a deal with YouTube in Germany to be the official channel partner for Nollywood company.\n\n" +
                    "In 2010, Njoku and his former partner Bastian Gotter launched NollywoodLove, a YouTube channel, which was profitable within two months of launch. That same year, thanks to an article by Sarah Lacy who worked at the time for Tech Crunch, NollywoodLove caught the attention of US-based venture capital fund Tiger Global who were interested in expanding their reach in emerging markets.\n\n" +
                    "Series A investment of \$3 million was secured from Tiger Global in 2010 and the company launched a stand-alone video-on-demand movie platform, iROKOtv, on 1 December 2011. The site drew in viewers from 178 countries around the world. Njoku and Gotter have since gone on to raise an additional \$22 million from international VCs, with inclusion from Investment AB Kinnevik and RISE Capital and have used the investment to build an extensive film catalog of 5,000 movies, launch offices in Lagos, New York, and London and invest in improving the company's technology resource. Iroko has gone to make other funding investment totalling $40 million \n\n" +
                    "In 2015, Njoku decided to focus the company's attention on an Android mobile app, rather than a streaming platform to combat broadband infrastructure problems that Africa poses.\n\n" +
                    "In July 2012, he was cited by Forbes Africa as one of the 'Ten Young African Millionaires to Watch'. On 29 August 2013, Njoku was named as the CNBC All Africa Business Awards Young Leader of the Year for West Africa. He has also been named as one of Fast Company's Top 1000 Most Creative People in Business.\n\n" +
                    "Spark\n" +
                    "In August 2013, alongside his business partners Bastian Gotter and Mary Remmy Njoku, Njoku launched a \$2 million investment vehicle for Lagos-based Internet start-ups called Spark. The company initially invested in 11 companies, including a drinks distribution company called Drinks.ng, a real-estate and property online letting agency called ToLet.com.ng, and a hotel room booking site, called Hotels.ng, which has gone on to raise \$1.2 million in VC investment from EchoVC Pan-Africa Fund and Omidyar Network. In 2015, Jason Njoku in a blog post officially announced they're letting go of four startups considered failed businesses: Bus.com.ng (an online bus ticketing service ), Insured.ng (an insurance comparison platform), Giddimint.com.ng (an online fashion store) and Christians.ng, an online dating platform for Christians.\n",
            R.drawable.jason),

            TechModel("Lina Ben Mhenni",
            "LINA BEN MHENNI (22 May 1983 – 27 January 2020)\n" +
                    "Lina Ben Mhenni was a Tunisian Internet activist, blogger and lecturer in linguistics at Tunis University. She was internationally recognised for her work during the 2011 Tunisian revolution and in the following years. Ben Mhenni's blog, A Tunisian Girl, is written in Arabic, English, and French. During the rule of former Tunisian President Zine El Abidine Ben Ali until 2011, Ben Mhenni was one of the few bloggers to blog using her real name rather than adopting a pseudonym to protect her identity. Her blog, as well as her Facebook and Twitter accounts, were censored under the Ben Ali regime.\n\n" +
                    "Ben Mhenni began posting photos and video of protests of those injured throughout Tunisia. In an effort to make the government responsible for its actions and to the people who were harmed in these uprisings, she visited local hospitals and took pictures of those harmed by police. In May 2010, Ben Mhenni was among the core organizers of a protest in Tunis against the government's suppression of media and censorship of the internet.\n\n" +
                    "As at January 2011, she covered the early weeks of the Tunisian Revolution from Sidi Bouzid Governorate in the interior of the country. Ben Mhenni was the only blogger present in the interior cities of Kasserine and Regueb when government forces massacred and suppressed protesters in the region. Her reports and posts provided uncensored information to other Tunisian activists and the international media.\n\n" +
                    "Since the Tunisian Revolution began and until she died, Ben Mhenni played a prominent role amongst Tunisia's bloggers and democracy activists. She participated in the interim government’s reforms to media and information laws, but resigned shortly after. She continued to work in tracking press freedom and human rights in the country.\n\n" +
                    "She was vocal against continuing corruption in the Tunisian regime, criticized the Islamist party Ennahda for a \"double discourse\" that espoused reactionary views on social media while its leaders presented a different image to traditional media, and demanded the release of Alaa Abdel-Fatah upon his arrest in October 2011. In a 2014 editorial for CNN, she wrote that her activism after Ben Ali's overthrow had led to her receiving death threats and requiring close protection of the police.\n\n" +
                    "Ben Mhenni stated that Tunisia's revolution \"cannot be called an internet revolution\", and insisted that the revolution against Ben Ali was fought \"on the ground\" through demonstrations and resistance. She also stated her belief that \"action in the digital world must be combined with actions in the real world.\" She was quoted as saying: “It is not enough to publish a status, or a video, or share a hashtag. You have to work in the field, meet people, and be present during the demonstrations.” \n\n" +
                    "She continued to act on her words until she died. Along with her father, she started an initiative to create libraries in prisons to promote culture and counter terrorism. In her final months, she denounced the state of hospitals in the Tunisian capital.\n",
            R.drawable.lina),

            TechModel("Ory Okolloh",
            "Ory Okolloh or Ory Okolloh Mwangi is a Kenyan activist, lawyer, and blogger. She earned an undergraduate degree in Political Science from the University of Pittsburgh and graduated from Harvard Law School in 2005. She is Director of Investments at Omidyar Network. She was formerly the Policy Manager for Africa with Google. In 2007, Okolloh co-created Ushahidi.\n\n" +
                    "In 2006 she co-founded the parliamentary watchdog site Mzalendo (Swahili: \"Patriot\"). The site sought to increase government accountability by systematically recording bills, speeches, MPs, standing orders, etc.\n\n" +
                    "When Kenya was engulfed in violence following a disputed presidential election in 2007, Okolloh co-created Ushahidi (Swahili: \"Witness\"), a website and tool that collected and recorded eyewitness reports of violence using text messages and Google Maps. The technology has since been adapted for expanded purposes (including monitoring elections and tracking pharmaceutical availability) and used in a number of other countries.\n\n" +
                    "Okolloh has a personal blog, Kenyan Pundit, which was featured on Global Voices Online. She has worked as a legal consultant for NGOs and has worked at Covington and Burling, the Kenya National Commission on Human Rights, and the World Bank.\n\n" +
                    "Okolloh was appointed on the Board of Thomson Reuters Founders Share Company, the body that acts as a guardian of the Thomson Reuters Trust Principles in May 2015.\n",
            R.drawable.ory),

            TechModel("Nii Quaynor",
            "Dr. Nii Quaynor pioneered Internet development and expansion throughout Africa for nearly two decades, establishing some of Africa's first Internet connections and helping set up key organizations, including the African Network Operators Group. He also was the founding chairman of AfriNIC, the African Internet numbers registry.\n\n" +
                    "He graduated from Dartmouth College in 1972 with a BA degree in Engineering Science and received his PhD in Computer Science in distributed systems in 1977 from State University of New York at Stony Brook, becoming one of the first African computer science PhD graduates and helped establish the Computer Science Department at the University of Cape Coast in Ghana, where he has taught since 1979.\n\n" +
                    "He was the first African to be elected to the board of the Internet Corporation for Assigned Names and Numbers (ICANN) and served as an at-large director of ICANN for the African region from 2000 to 2003.\n\n" +
                    "He worked with Digital Equipment Corporation (DEC) U.S.A, from 1977 to 1992, and in 1993 returned to Ghana to establish the first ISP in West Africa, operated by Network Computer Systems (NCS). NCS established several local and wide area network infrastructures for companies, provided technical services to Telecom companies, and assisted other countries to gain Internet access.\n\n" +
                    "In 2006 he established one of first ICANN Accredited Domain Registrars in Africa, Ghana Dot Com (GDC), and has taught microprocessors with International Center for Theoretical Physics (ICTP) in several developing countries.\n\n" +
                    "Nii is convener of AfNOG, a network technology transfer institution since 2000, and has served on several boards and commissions including ICANN, UN ICT Task Force, IGF-MAG, University of Ghana Council, Ghana News Agency (GNA), National Identification Authority (NIA), ICANN Strategy Panel on Public Responsibility, and the Global Commission on Internet Governance (GCIG). He is a member of GhiPPS board, a member of the Electronic Communications Tribunal and patron of ISOC’s Ghana Chapter. He is the former Chairman of the Board of National IT Agency (NITA) in Ghana, the Founding Chairman of AfriNIC as well as a founding member of AfricaCERT and WACREN.\n\n" +
                    "Nii received the Internet Society’s prestigious Jonathan Postel Service Award for pioneering work to advance Internet in Africa in December 2007, and was inducted into the Internet Hall of Fame in August 2013 for his pioneering role in the development of the Internet in Africa. He was also the recipient of the the Osagyefo Kwame Nkrumah Genius Award for Information Communication Technology in Dec 2014, and was awarded ICANN’s Multi-Stakeholder Ethos award in June 2015. He is affectionately referred to as “The Father of Internet in Africa”.\n\n" +
                    "He remains the Chairman of Ghana Dot Com (GDC) and Professor of Computer Science at University of Cape-Coast, Ghana where, in 1979, he established the Computer Science Department.\n",
            R.drawable.nii),

            TechModel("Mbuana Alliy",
            "Mbwana Alliy is the founder and managing partner at Savannah Fund, an Africa focused Technology Venture Capital fund seed investments in e-commerce, gaming, education technology and social networking. \n\n" +
                    "He is passionate about product development and launching new ventures in technology with an application to emerging and frontier markets. He is an experienced Product Manager within consumer web, enterprise Software & SaaS. He is originally from Tanzania and has lived and worked in 3 continents (USA, Europe and Africa). He has a Bachelor's Engineering degree from Bristol University and an MBA from Stanford Graduate school of Business.\n\n" +
                    "As of 2019, he has overseen 30 investments in Africa in 7 countries (Kenya, Uganda, South Africa, Zimbabwe Nigeria, Ethiopia and Ghana). These companies have generated over 400 full time jobs and raised over \$60 Million in venture financing. Savannah Fund is headquartered in Mauritius with Offices in Tanzania and Kenya and satellite offices in Silicon Valley, Hong Kong, Cape Town and Lagos.\n\n" +
                    "Mbwana stared invested as an Associate and Entrepreneur in Residence (EIR) for i/o ventures, a mentor-based venture capital firm based in Silicon Valley where he assists with seed and early-stage startup that are incubated as part of an accelerator program, he contributes in sourcing new deals and helping out in a variety of functions for the incubated startups inc. business development, product development, strategy and customer insights.\n\n" +
                    "In his work in building technology ecosystems and bridges between he has co-taught classes and spoken about Africa technology, entrepreneurship and venture capital at University of Cape Town, University College London and Stanford Graduate School of Business. He has also taught at the VC unlocked program with 500Startups and at Draper University of Heroes.\n\n",
            R.drawable.alliy),

            TechModel("Jepchumba",
            "This is the biography of Jepchumba",
            R.drawable.jep),

            TechModel("Mteto Nyeti",
            "Mteto Nyati was born from humble beginnings in Umtata, a poor town in the Eastern Cape, a province of South Africa, during the height of apartheid, but he refused to allow his circumstances to define him.\n\n" +
                    "By remaining true to himself from an early age, embracing who he is, a term he describes as personal mastering, focusing on the things he can change and sticking to his core values of family, fairness, excellence and integrity, his career has rapidly progressed. \n\n" +
                    "The mechanical engineer has held various leadership positions at the South African operations of multinational companies, such as IBM and Microsoft where he has fine-tuned and refined his leadership style to become a master strategist, developing a reputation as a turnaround specialist and ethical leader.\n\n" +
                    "From Microsoft, Nyati joined pan-African telecommunications network provider MTN and in 2017, South African-listed Allied Electronics Corporation Limited (Altron), where he is currently CEO.\n\n" +
                    "The highly self-aware and introverted businessman has transformed Altron into a serious contender in the technology space globally with plans to expand into the Netherlands, Malaysia and India.\n\n" +
                    "In less than three years, he has more than doubled Altron’s valuation taking it to just over $642 million. \n",
            R.drawable.mteto),

            TechModel("Funke Opeke",
            "Funke Opeke is a Nigerian electrical engineer, founder of Main Street Technologies and Chief Executive Officer of Main One Cable Company, a communications services company based in Lagos State, south-western Nigeria. Her company called MainOne is West Africa's leading communications services and network solutions provider.\n\n" +
                    "Funke Opeke attended Queens School (girls only) in Ibadan, Oyo state, Nigeria. She grew up in Ibadan, the capital city of Oyo State, although, she is a native of Ile- Oluji, Ondo state. Born into a family of 9, her father was the first Nigerian director of the Cocoa Research Institute of Nigeriawhile her mother was a teacher.\n\n" +
                    "Funke Opeke obtained a bachelor's and a master's degree in Electrical Engineering from Obafemi Awolowo University and Columbia University, respectively. After she graduated from Columbia University, she followed with a career in ICT in the United States as an executive director with the wholesale division of Verizon Communications in New York City. In 2005, she joined MTN Nigeria as chief technical officer (CTO). She served as adviser at Transcorp and chief operating officer of NITEL for a brief period.\n\n" +
                    "After moving back to Nigeria, Funke Opeke started MainOne in 2008, when she noticed the poor internet connectivity in Nigeria. MainOne is West Africa's leading communication services and network solutions provider. The company built West Africa's first privately owned, open access 7,000-kilometer undersea high-capacity cable submarine stretching from Portugal to West Africa with landings along the route in Accra (Ghana), Dakar (Senegal) in 2019, Abidjan (Côte d'Ivoire) in 2019 and Lagos (Nigeria). Her desire to add value to her home country birthed Africa's biggest cable company. After pledging all her savings, facing more challenges of raising capital for the start-up cable business, carrying out in-depth foundational works, feasibility studies, business plans, and technical plans, Main One Cable Company become more tangible. In 2015, her company started operations of MDXi reputed to be Nigeria's largest Tier III Data Center, also extending a submarine cable from Lagos into Cameroon. Her achievements are a source of inspiration to many. Funke is the inventor of Mainstreet Technologies, the developer of MainOne cable, a leading provider of network solutions in West Africa.\n\n",
            R.drawable.funke),

            TechModel("Hilda Moroa",
            "Hilda Moraa is currently the CEO & Founder of Pezesha, A Digital Financial Marketplace for the underserved in Africa. \n\n" +
                    " She earned her Masters in Entrepreneurship & a Business Information Technology Degree from Strathmore University, Nairobi, Kenya. She is an Award-winning entrepreneur and the author of “A Kenyan startup Journey”. She has over a decade worth of experience in Fintech and working with multinationals to develop innovations across Africa. Prior to Pezesha, She was the Founder & CEO of WezaTele, a value add mobility service provider in Fintech & Supply chain sector that was started in 2009 and successfully acquired in 2015. She was among of the founding team of iHub Research, an initiative under iHub, Nairobi’s 1st Innovation Hub. She was listed as of the top 30 innovators in Africa in 2018 by Quartz Africa. She was the keynote speaker at the GES 2015 when President Barrack Obama was in Kenya for the event and still feel very blessed to have shared a podium with him as one of my role models.\n",
            R.drawable.hilda),

            TechModel("Rebecca Enonchong",
            "Rebecca Enonchong (born in1967) is a Cameroonian born technology entrepreneur and also the founder and CEO of AppsTech. She is best known for her work promoting technology in Africa.\n\n" +
                    "Enonchong was born in Cameroon in 1967. Her father was Dr. Henry Ndifor Abi Enonchong, who was a well-known barrister in Cameroon. While Enonchong was growing up in Cameroon, her father helped create the Federal Cameroon Bar Association and its successor, the Cameroon Bar Association.\n\n" +
                    "In her teens, Enonchong moved to the US with her family. While studying, she took up a job selling door-to-door newspaper subscriptions from the age of 15. She later became a manager at the same company at the age of 17. Enonchong also attended the Catholic University of America, where she graduated with a Bachelor of Science degree and also a Master of Science degree in Economics.\n\n" +
                    "After finishing her education, Enonchong went on to work for a number of organizations including Inter-American Development Bank (IaDB) and Oracle Corporation.\n\n" +
                    "In 1999, Enonchong founded the company AppsTech, a Bethesda, Maryland-based global provider of enterprise application solutions. AppsTech is an Oracle Platinum Partner and has customers in over 40 countries.\n\n" +
                    "AppsTech opened offices in several countries, including Enonchong's native Cameroon. She describes the experience as having been difficult and having led to the closure of AppsTech subsidiaries.\n\n" +
                    "In 2002, The World Economic Forum of Davos, Switzerland named Enonchong a Global Leader for Tomorrow (GLT) along with other tech entrepreneurs such as Google co-founder Larry Page and Salesforce.com CEO Marc Benioff.\n\n" +
                    "In 2013, Enonchong was recognized as a finalist for the African digital woman award. In March 2014, Forbes listed her as one of the ‘10 Female Tech Founders to Watch in Africa’.\n\n" +
                    "Enonchong has also gained notoriety as one of the more followed sources for African tech news on Twitter, with over 30 thousand followers. Her handle, @Africatechie, has become a nickname for Enonchong in IT circles.\n",
            R.drawable.rebecca)



    )
}